#!/bin/bash

_term() {
    echo "Caught SIGTERM, unlinking dests"
    cleanup
}

cleanup() {
    rm -rf ${PREFIX}/dest
}

setup() {
    if [[ -d "${PREFIX}/dest" ]]
    then
        mv ${PREFIX}/dest ${PREFIX}/dest.queue
    fi
}

create_links() {
    mkdir -vp ${PREFIX}/dest/{user,system}

    TARGETS=($MOUNTS)

    for CURRENTDEST in ${TARGETS[@]}
    do
        ln -s "$(echo ${!CURRENTDEST} | awk -F\: '{print $2}')" "${PREFIX}/dest/$(echo ${!CURRENTDEST} | awk -F\: '{print $1}')"
        echo "Linked target ${CURRENTDEST} ( $(echo ${!CURRENTDEST} | awk -F\: '{print $1}') ) to $(echo ${!CURRENTDEST} | awk -F\: '{print $2}')"
    done
}

move_queue() {
    if [[ -d "${PREFIX}/dest.queue" ]]
    then
        echo "Moving queue"
        mv ${PREFIX}/dest.queue ${PREFIX}/dest
    fi
}

main() {
    echo "Root prefix is set to: ${PREFIX}"

    setup
    create_links
    move_queue

    sleep infinity &

    child=$!
    wait "$child"
}

# service logic for kanrisha

trap _term SIGTERM
trap _term SIGINT

. "${PREFIX}/etc/kanrisha.d/available/destlink/destlink.conf"

main
